[FEAT] 메인 페이지 퍼블리싱
Project-aniwhere/Aniwhere-FE pull request #12
Opened 2024-10-28 13:40 UTC by LEEGURTS

## 이슈 번호, 혹은 추가한 기능에 대해 설명해주세요.
#11

## 작업 상세 내용

- [x] 메인페이지 퍼블리싱
- [x] 댓글 컴포넌트 퍼블리싱
- [x] SVG 추가

## 기타 내용
공통 컴포넌트 고도화 필요
서버/클라이언트 컴포넌트 기능 확고하게 분리 필요

2024-10-30 13:37 UTC, yujinyny reviewed
근성님 PR 제목 바꿔주시면 감사하겠습니다!

2024-10-30 13:37 UTC, yujinyny commented on src/component/common/comment/comment.tsx
> +/* eslint-disable @next/next/no-img-element */
eslint rule에 추가하면 좋을거 같습니다!

2024-10-30 13:37 UTC, yujinyny commented on src/type/content-slider.d.ts
> +}
type 폴더 내 컴포별트 별로 파일 분리 하면 파일이 너무 많아질 거 같아서 다른 방법이 없을까요?

2024-10-30 13:37 UTC, yujinyny commented on src/asset/svg/heart/heart-svg.tsx
> +  width = '21',
width, height rem 단위로 지정하면 좋을 거 같습니다.

2024-10-30 13:45 UTC, yujinyny requested changes
근성님 PR 제목 바꿔주시면 감사하겠습니다!

2024-10-30 13:54 UTC, LEEGURTS commented on src/component/common/comment/comment.tsx
> +/* eslint-disable @next/next/no-img-element */
기본적으로는 안쓰는게 맞아서 저 컴포넌트에만 img를 쓰는게 최적화에 좋다고 판단해서 넣어놨습니다

2024-10-30 13:55 UTC, LEEGURTS commented on src/asset/svg/heart/heart-svg.tsx
> +  width = '21',
맞습니다 rem으로 돌려놓겠습니다

2024-10-30 14:14 UTC, LEEGURTS commented on src/type/content-slider.d.ts
> +}
나중에 고민하는걸로 결정입니다

2024-10-31 13:43 UTC, yujinyny approved these changes

2024-11-01 06:48 UTC, merged