Feat/login publish
Project-aniwhere/Aniwhere-FE pull request #16
Opened 2024-10-29 11:22 UTC by Programmer-JK

## 이슈 번호, 혹은 추가한 기능에 대해 설명해주세요.
login 모달 퍼블리싱 추가

## 작업 상세 내용

- [x] 로그인 모달 퍼블리싱
- [ ] 로그인 페이지, 모달 방식 구축

## 기타 내용

2024-10-30 13:44 UTC, yujinyny requested changes

2024-10-30 13:44 UTC, yujinyny commented on src/component/login/login-container.tsx
> +        </button>
Input, Button 공통 컴포넌트로 따로 빼주실 수 있을까요?

2024-10-30 13:46 UTC, yujinyny requested changes
PR 제목 바꿔주시면 감사하겠습니다!

2024-11-03 09:45 UTC, Programmer-JK commented on src/component/login/login-container.tsx
> +        </button>
따로 공통 컴포넌트로 수정해서 올렸습니다

2024-11-04 04:36 UTC, yujinyny approved these changes

2024-11-04 05:01 UTC, merged