Feat/weekly ani publish
Project-aniwhere/Aniwhere-FE pull request #25
Opened 2024-11-04 07:39 UTC by yujinyny

## 이슈 번호, 혹은 추가한 기능에 대해 설명해주세요.
[#21](https://github.com/Project-aniwhere/Aniwhere-FE/issues/21)

## 기타 내용
추후 API 연동 작업하면서 이미지 최적화 및 스켈레톤 UI 작업 진행할 예정입니다.

2024-11-04 10:47 UTC, LEEGURTS requested changes
서버 컴포넌트로 이관 가능한게 많아보이기는 하는데, 이 부분은 다 최적화 영역이라 귀찮으면 안하셔도 될거같긴합니다!

2024-11-04 10:47 UTC, LEEGURTS commented on src/app/weekly/page.tsx
> +  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
api가 어떻게 나올지는 모르겠지만,  동적 라우팅을 도입해보는것도 좋지 않을까요?

장점으로는 기간별로의 ssg/ssr이 가능하다는 점이 있겠네요

2024-11-04 10:47 UTC, LEEGURTS commented on src/app/weekly/page.tsx
> +'use client';
동적 라우팅을 활용하면 서버 컴포넌트로 이관 가능해보여요

2024-11-04 10:47 UTC, LEEGURTS commented on src/app/weekly/page.tsx
> +    <div className='w-full max-w-[1200px] mx-auto pt-[96px] pb-7 flex flex-col gap-10'>
component/common/layout/main-layout.tsx 활용 가능해보이는데 어렵다면 안해주셔도 댑니다

2024-11-04 10:47 UTC, LEEGURTS commented on src/component/common/picker/year-item.tsx
> +      onClick={() => handleChangeYear(year)}
위의 서버컴포넌트 이관에 성공했다면 이 컴포넌트도 func를 넘겨서 RCC로 확정 짓는게 아닌, RSC로 이관 가능해보여요

2024-11-04 10:47 UTC, LEEGURTS commented on src/component/common/tag/tag.tsx
> +      className={`${baseStyles} ${sizeStyles[size]} ${colorStyles[state]}`}
오 깔끔해서 좋은거 같아요. 저도 이렇게 바꿀수 있는건 바꿔야 겠네요!

2024-11-04 10:47 UTC, LEEGURTS commented on src/component/weekly/daily-container.tsx
> +      <ul className={'flex flex-col gap-3'}>
변수가 아니면 굳이 {} 괄호로 가둘이유는 없어보여요

2024-11-04 10:47 UTC, LEEGURTS commented on src/component/weekly/daily-item.tsx
> +        width={151.43}
음 이 이미지 크기는 뭐져

2024-11-04 10:47 UTC, LEEGURTS commented on src/component/weekly/daily-item.tsx
> +        className='rounded hover:scale-105 duration-200'
아마 컴포넌트 사이즈를 정하고 싶으셨던걸로 보이는데 width={0} height={0} size={여기서 다운로드하는 이미지 크기 결정!} 주고 className을 통해 컴포넌트 크기 조절 가능해요

2024-11-04 10:47 UTC, LEEGURTS commented on src/component/weekly/weekly-container.tsx
> +  weeklyList: { [key: string]: DailyAniProps[] };
Typescript에 이런걸 해결할 Record라는 문법이 있습니다!

2024-11-04 10:47 UTC, LEEGURTS commented on src/constant/dummy.ts
더미가 너무 커요... 조금만 작게 해주세요 ㅠㅠ

2024-11-06 09:41 UTC, yujinyny commented on src/app/weekly/page.tsx
> +    <div className='w-full max-w-[1200px] mx-auto pt-[96px] pb-7 flex flex-col gap-10'>
일단 추가하긴 했는데 해당 페이지는 layout 보다 max-width를 작게 잡아서 사용하지 않는 거랑 다름이 없어요. 공통 레이아웃 크기에 대해 정해보는게 좋겠네요!

2024-11-06 10:11 UTC, yujinyny commented on src/app/weekly/page.tsx
> +  const [selectedYear, setSelectedYear] = useState(new Date().getFullYear());
동적 라우팅 적용은 pr을 따로 만들겠습니다~

2024-11-06 10:49 UTC, yujinyny commented on src/component/weekly/daily-item.tsx
> +        className='rounded hover:scale-105 duration-200'
찾아보니 이런 결과가 나왔습니다.

`images의 sizes 속성은 반응형 디자인에서 사용됩니다. 예를 들어, 뷰포트의 크기나 다른 조건에 따라 이미지의 크기를 다르게 적용하는 데 사용됩니다. 하지만 sizes 속성만으로 이미지를 최적화할 수는 없습니다. 이미지의 고정된 크기(width, height)가 제대로 설정되지 않으면, sizes가 작동하지 않거나, 브라우저가 이미지를 올바르게 렌더링할 수 없게 됩니다.`

이거에 대해선 어떻게 생각하시나요?

2024-11-06 10:50 UTC, yujinyny commented on src/component/weekly/daily-item.tsx
> +        width={151.43}
실데이터의 섬네일 규격을 모르기 때문에 현재 샘플 데이터 섬네일의 크기로 지정한 값입니다.
위 pr 디스크립션에 `추후 API 연동하면서 이미지 최적화 및 스켈레톤 UI 작업 진행할 예정입니다.` 남겨두기도 하였습니다.

2024-11-09 09:23 UTC, Programmer-JK approved these changes

2024-11-09 09:23 UTC, Programmer-JK commented on src/app/weekly/page.tsx
> +    <div className='w-full pt-[96px] px-8 flex flex-col gap-4'>
pt-[96px] 보다 pt-24해서 pixel 단위가 아닌 rem단위로 하는 건 어떠신가요?

2024-11-09 11:32 UTC, LEEGURTS commented on src/component/weekly/daily-item.tsx
> +        className='rounded hover:scale-105 duration-200'
https://github.com/vercel/next.js/discussions/18474#discussioncomment-5501724
해당 글에 의하면 2023년부터는 이 방법을 사용하고 있다고 합니다. 

혹시 해당 원문을 볼 수 있나여

2024-11-09 11:32 UTC, LEEGURTS commented on src/app/weekly/page.tsx
> +    <div className='w-full pt-[96px] px-8 flex flex-col gap-4'>
좋은 의견 같습니다

2024-11-09 11:46 UTC, LEEGURTS approved these changes

2024-11-10 08:16 UTC, yujinyny commented on src/component/weekly/daily-item.tsx
> +        className='rounded hover:scale-105 duration-200'
답변은 지피티를 활용했습니다.

`width={0}`, `height={0}`, `sizes='15%'`와 같은 설정은 일부 개발자들이 **이미지 레이아웃을 유연하게** 만들기 위해 사용하기도 합니다. 하지만 이 방식은 권장되지 않으며, **의도치 않은 부작용**을 일으킬 수 있습니다. 자세히 설명하겠습니다.

### 1. `width`와 `height`를 `0`으로 설정하는 문제점
Next.js의 `next/image` 컴포넌트는 **레이아웃 시프트 방지**를 위해 **고정된 가로, 세로 비율(aspect ratio)**를 사용합니다. `width`와 `height`를 `0`으로 설정하면 다음과 같은 문제들이 발생할 수 있습니다:

- **레이아웃 시프트 발생**: 이미지 로드 전에 크기를 알 수 없으므로, 로딩 중 페이지 레이아웃이 변경될 수 있습니다.
- **SEO 및 접근성 문제**: 이미지 크기가 `0`으로 설정되면 브라우저는 이를 **잘못된 이미지**로 간주할 수 있습니다. 이는 검색 엔진과 접근성 도구에서도 부정적인 영향을 줄 수 있습니다.
- **콘텐츠 크기 계산 오류**: `sizes` 속성에 따라 반응형 크기를 설정하더라도, 브라우저는 `width`와 `height`가 없는 이미지를 적절히 계산하지 못할 수 있습니다.

### 2. `sizes`만 사용하려는 의도는?
`sizes='15%'`는 뷰포트 너비의 15% 크기로 이미지를 표시하려는 의도일 것입니다. 하지만 이 경우에도 `width`와 `height`는 **비율 유지를 위해 필요**합니다.

### 3. 올바른 사용 예시 (`fill` 속성 활용)
만약 **반응형 레이아웃**에서 이미지 크기를 동적으로 설정하고 싶다면, `fill` 속성을 사용하는 것이 더 좋은 방법입니다:

```tsx
<div style={{ position: 'relative', width: '100%', height: '200px' }}>
  <Image
    src='/path/to/image.jpg'
    alt='Responsive image'
    fill
    sizes='15vw'
    style={{ objectFit: 'cover' }}
  />
</div>
```

#### 장점
- **자동 크기 계산**: `fill` 속성을 사용하면 부모 요소의 크기에 맞춰 이미지가 자동으로 조정됩니다.
- **레이아웃 시프트 방지**: 부모 요소에 고정된 높이(`height`)를 지정하면 안정적인 레이아웃을 유지할 수 있습니다.
- **objectFit 활용 가능**: `objectFit` 속성으로 `cover`, `contain` 등 다양한 스타일을 적용할 수 있습니다.

### 4. 반응형 이미지 예시 (`sizes` 활용)
`width`와 `height`를 적절히 설정하면서 `sizes` 속성도 함께 사용하는 것이 좋습니다:

```tsx
<Image
  src='/path/to/image.jpg'
  alt='Sample image'
  width={800}
  height={600}
  sizes='(max-width: 768px) 100vw, 15vw'
  style={{ objectFit: 'cover' }}
/>
```

#### 장점
- **비율 유지**: `width`와 `height`는 비율을 유지하면서 반응형으로 이미지를 조정합니다.
- **반응형 최적화**: `sizes` 속성을 통해 뷰포트 크기에 맞는 이미지를 로드합니다.
- **성능 개선**: Next.js는 `sizes` 속성에 따라 최적의 이미지를 자동으로 선택하여 전송합니다.

### 결론
- `width={0}`와 `height={0}` 설정은 피해야 합니다. 이는 Next.js의 이미지 최적화 및 레이아웃 계산 기능을 제대로 활용하지 못하는 방법입니다.
- 반응형 레이아웃이 필요하다면, `fill` 속성이나 적절한 `width`, `height`와 함께 `sizes` 속성을 사용하는 것이 가장 좋습니다.
- 최신 Next.js에서는 `next/image`의 기능이 강화되었으므로, 이를 최대한 활용하는 것이 성능 및 사용자 경험에 유리합니다.

이 방법으로 이미지를 구현하면, **반응형 디자인**과 **성능 최적화**를 모두 달성할 수 있습니다.

2024-11-10 08:17 UTC, yujinyny commented on src/component/weekly/daily-item.tsx
> +        className='rounded hover:scale-105 duration-200'
next 공식문서에서도 확인했는데,
sizes 활용하고 싶다면 width, height를 0으로 지정하는게 아닌 fill 속성을 활용하는게 맞지 않나 싶습니다.

https://nextjs.org/docs/pages/api-reference/components/image#width

2024-11-10 08:20 UTC, merged