[FEAT] 회원가입 페이지 퍼블리싱
Project-aniwhere/Aniwhere-FE pull request #27
Opened 2024-11-04 11:43 UTC by Programmer-JK

## 이슈 번호, 혹은 추가한 기능에 대해 설명해주세요.
회원가입 페이지 퍼블리싱

## 작업 상세 내용
- [ ] 회원가입 페이지 퍼블리싱
- [ ] common datepicker 생성
- [ ] signUp 페이지 생성

## 기타 내용
datepicker를 위한 react-calender, moment 추가 설치

2024-11-05 04:05 UTC, LEEGURTS requested changes
스타일링 깔끔해지신게 느껴지십니다!
엄청난 발전형이시군요

2024-11-05 04:05 UTC, LEEGURTS commented on src/component/common/datepicker/custom-datepicker.tsx
> +  const [nowDate, setNowDate] = useState<string>(`${placeholder}`); // 초기값 설정
얘는 그냥 리터럴 문자열 쓸게 아니라 바로 넣으면 되는거 아닌가여

2024-11-05 04:05 UTC, LEEGURTS commented on src/component/common/datepicker/custom-datepicker.tsx
> +  const [placeholderColor, setPlaceholderColor] = useState('text-gray-400');
음... 뭔가 이상해요... 다른 방안이 있을듯 해요

2024-11-05 04:05 UTC, LEEGURTS commented on src/component/common/datepicker/custom-datepicker.tsx
> +      <div className={`absolute left-0 ${isOpen ? 'block' : 'hidden'}`}>
이러면 아마 hidden 상태일때 클릭이 씹힐거같아요. 조건부 렌더링으로 교체하는게 어떨까요

2024-11-05 04:05 UTC, LEEGURTS commented on src/component/common/datepicker/custom-datepicker.tsx
> +        className={`${className} ${placeholderColor} text-left w-72 p-3 border border-gray-300 rounded-lg bg-gray-50`}
className은 뒤에 붙여야 적용될 듯 해요

2024-11-05 04:05 UTC, LEEGURTS commented on src/component/common/datepicker/custom-datepicker.tsx
> +      <div className={`absolute left-0 ${isOpen ? 'block' : 'hidden'}`}>
정확히는 해당 컴포넌트 아래에 가려진 내용물에 대한 클릭이 무시될 염려가 있어요

2024-11-05 04:05 UTC, LEEGURTS commented on src/component/common/input/radio-input.tsx
> +      className={`${className} w-full p-3 border border-gray-300 rounded-lg bg-gray-50`}
애도 마찬가지입니다

2024-11-05 04:05 UTC, LEEGURTS commented on src/app/signUp/page.tsx
url이 소문자였으면 좋겠습니다

2024-11-05 04:05 UTC, LEEGURTS commented on src/app/signUp/page.tsx
> +            <IconButton Icon={KakaotalkSvg} height='3rem' width='3rem' />
아마 컴포넌트를 넘기려는 의도 같은데 children으로 넘기는게 더 적합해보여요

2024-11-05 04:05 UTC, LEEGURTS commented on src/app/signUp/page.tsx
> +            <IconButton Icon={KakaotalkSvg} height='3rem' width='3rem' />
props로 넘기면 client component로 확정되어버려서 children이 나아보입니다

2024-11-05 04:32 UTC, LEEGURTS commented on src/app/signUp/page.tsx
> +            <DefaultDatepicker
DatePicker 라이브러리를 활용하셔서 만드셨는데 이 부분 외에는 나머지는 server-action으로 해결해서 전체 다 RSC로 이관 가능해보여요. 이 부분도 input 태그 스타일링과 form 사용하면 서버로 완전히 넘겨 줄 수 있을거같아요

2024-11-05 05:00 UTC, LEEGURTS commented on src/app/signUp/page.tsx
> +            <DefaultDatepicker
캘린더 스타일링이 어렵다는 큰 문제가 있긴 하네요 ㅠ

2024-11-05 08:14 UTC, Programmer-JK commented on src/component/common/datepicker/custom-datepicker.tsx
> +  const [nowDate, setNowDate] = useState<string>(`${placeholder}`); // 초기값 설정
placeholder를 리터럴 문자열로 쓴 이유는 datepicker를 생년월일말고도 다양한 부분에서 사용 가능성이 있기 때문입니다.

2024-11-05 08:20 UTC, Programmer-JK commented on src/component/common/input/radio-input.tsx
> +      className={`${className} w-full p-3 border border-gray-300 rounded-lg bg-gray-50`}
지금 확인해서 테스트 돌려봤는데, className 앞에 둬도 적용이 잘 됩니다. 그래도 코드 일관성을 위해 수정해놓겠습니다.

2024-11-05 08:21 UTC, Programmer-JK commented on src/app/signUp/page.tsx
네 바로 수정하겠습니다

2024-11-05 08:56 UTC, Programmer-JK commented on src/app/signUp/page.tsx
> +            <DefaultDatepicker
기존 react-datepicker 라이브러리가 디자인이나 기능적으로 사용이 어려운 부분이 있어서 react-calendar를 가져와서 만들어봤습니다. 안그래도 서버 컴포넌트 공부하고 있는데, 아직까진 가닥이 안잡히고 있어요. 한번 그 방향으로 찾아보긴 해볼게요.

2024-11-05 08:59 UTC, Programmer-JK commented on src/component/common/datepicker/custom-datepicker.tsx
> +      <div className={`absolute left-0 ${isOpen ? 'block' : 'hidden'}`}>
조건부 렌더링으로 교체해서 테스트해보겠습니다

2024-11-06 11:10 UTC, yujinyny requested changes

2024-11-06 11:10 UTC, yujinyny commented on src/app/signup/page.tsx
> +        <form className='space-y-4'>
한 파일에 너무 많은 코드가 담겨있어 컴포넌트를 분리하여 가독성을 높이는게 어떨까요! (ex. SignupForm)

2024-11-06 11:10 UTC, yujinyny commented on src/type/common.d.ts
> +export interface IconButtonProps extends CommonButtonProps {
`CommonButtonProps` 대신 `React.ButtonHTMLAttributes<HTMLButtonElement>`를 사용하면 버튼 기본 속성 타입을 직접 작성하지 않고 정의할 수 있습니다.

2024-11-06 11:10 UTC, yujinyny commented on src/type/common.d.ts
> +export interface RadioInputProps extends CommonInputProps {
여기도 `CommonInputProps` 대신 `React.InputHTMLAttributes<HTMLInputElement>`요!

2024-11-06 11:10 UTC, yujinyny commented on src/type/common.d.ts
> +export interface IconButtonProps extends CommonButtonProps {
그리고 컴포넌트에는 `...props`로 내려주면 편리합니다.

2024-11-06 11:10 UTC, yujinyny commented on src/component/common/button/hover-color-button.tsx
> +      className={`bg-aniviolet3 text-white rounded-lg hover:bg-purple-700 transition-color ${className}`}
HoverColorButton의 className을 작성한 것을 보니 사이즈(padding)때문인거 같은데, className말고 size props (ex. small, medium, large)를 작성하는 것이 재사용성을 훨씬 높여줄거 같습니다. 해당 컴포넌트를 사용할 때마다 일일이 className으로 padding을 지정해줘야 한다면 공통 컴포넌트에는 맞지 않는거 같아요!

2024-11-06 11:10 UTC, yujinyny commented on src/component/common/button/hover-color-button.tsx
> +      className={`bg-aniviolet3 text-white rounded-lg hover:bg-purple-700 transition-color ${className}`}
다른 공통 컴포넌트들도 className을 prop으로 작성하는것은 컴포넌트 사용하기에 불편할 거 같습니다 🥲

2024-11-06 11:32 UTC, LEEGURTS commented on src/component/common/datepicker/custom-datepicker.tsx
> +  const [nowDate, setNowDate] = useState<string>(`${placeholder}`); // 초기값 설정
useState(placeholder)와 useState(`${placeholder}`) 와 결과적으로는 어떤 차이인지 잘 모르겠어서 그런데 예시가 있을까요?

2024-11-06 11:32 UTC, LEEGURTS commented on src/component/common/button/hover-color-button.tsx
> +      className={`bg-aniviolet3 text-white rounded-lg hover:bg-purple-700 transition-color ${className}`}
> 다른 공통 컴포넌트들도 className을 prop으로 작성하는것은 컴포넌트 사용하기에 불편할 거 같습니다 🥲

className이 필수가 아니고  옵셔널해서 컴포넌트 사용에 불편함이 생길일은 적습니다! 스타일링의 강제를 방지하고자 보통은 className을 전달해서 컨테이너에 대입하는 경우가 많으며 그 예시로 tailwindcss 기반인 shadcn을 보면 제공하는 대부분의 컴포넌트는 className을 적을 수 있는 여지를 남겨줍니다.

아마 정해진 값으로 정확하고 일정한 padding을 넣자 라는 의미로 이해했는데 이 부분은 tailwind.config.js 에 해당 옵션들을 작성해주는것이 더 좋아보입니다.

2024-11-06 11:32 UTC, LEEGURTS commented on src/type/common.d.ts
> +export interface RadioInputProps extends CommonInputProps {
> 여기도 `CommonInputProps` 대신 `React.InputHTMLAttributes<HTMLInputElement>`요!

오 저도 배워갑니다

2024-11-06 13:40 UTC, Programmer-JK commented on src/component/common/datepicker/custom-datepicker.tsx
> +  const [nowDate, setNowDate] = useState<string>(`${placeholder}`); // 초기값 설정
지금 테스트를 해보니까 useState(placeholder) 이래도 되네요. 그렇게 수정해놓을게요

2024-11-06 13:41 UTC, Programmer-JK commented on src/app/signup/page.tsx
> +        <form className='space-y-4'>
form을 분리해서 가독성 높여볼게요! 감사합니다

2024-11-06 14:51 UTC, Programmer-JK commented on src/type/common.d.ts
> +export interface IconButtonProps extends CommonButtonProps {
컴포넌트에 있는 type은 공통 컴포넌트에 기본값을 넣어야 될 것 같아서 type = 'submit' 같이 남아있는 코드 남겨놨습니다

2024-11-07 12:16 UTC, Programmer-JK commented on src/app/signUp/page.tsx
> +            <IconButton Icon={KakaotalkSvg} height='3rem' width='3rem' />
children으로 수정했습니다.

2024-11-07 12:17 UTC, Programmer-JK commented on src/type/common.d.ts
> +export interface RadioInputProps extends CommonInputProps {
네, 수정했습니다.

2024-11-07 12:19 UTC, Programmer-JK commented on src/component/common/button/hover-color-button.tsx
> +      className={`bg-aniviolet3 text-white rounded-lg hover:bg-purple-700 transition-color ${className}`}
이 부분은 각 페이지마다 padding을 주는 값이 바뀔 것 같아서 props로 빼놓긴 했었습니다. tailwind.config.js로 작성한다고 하면 공통적으로 정해야할 style에 대해 한번 대화를 하는 게 좋을 것 같아요

2024-11-08 09:00 UTC, LEEGURTS approved these changes

2024-11-10 08:27 UTC, yujinyny approved these changes
고생하셨습니다 !!

2024-11-10 12:42 UTC, merged