[Refactor] 최적화 진행
Project-aniwhere/Aniwhere-FE pull request #29
Opened 2024-11-06 06:14 UTC by LEEGURTS

## 이슈 번호, 혹은 추가한 기능에 대해 설명해주세요.
#28

## 작업 상세 내용

- [x] 폰트 최적화
- [x] 필요없는 라이브러리 의존 제거
- [x] 캐러셀 휴리스틱하게 구현

## 기타 내용

2024-11-06 11:24 UTC, yujinyny requested changes

2024-11-06 11:24 UTC, yujinyny commented on src/component/common/carousel/bullet-item.tsx
> +        className={
이 부분 이렇게 작성하면 적용이 안되나요?
`w-full h-full rounded-full ${isCurrent ? 'bg-aniviolet2' : 'bg-gray-300'}`

2024-11-06 11:24 UTC, yujinyny commented on src/component/common/carousel/carousel-container.tsx
> +  const [isMobile, setIsMobile] = useState(false);
다른 곳에서 활용할 수도 있을거 같아서 이거 전역 상태로 관리하면 좋을거 같아요!

2024-11-06 11:33 UTC, LEEGURTS commented on src/component/common/carousel/bullet-item.tsx
> +        className={
반영 됩니다! 이렇게 해야겠네요

2024-11-06 11:35 UTC, LEEGURTS commented on src/component/common/carousel/carousel-container.tsx
> +  const [isMobile, setIsMobile] = useState(false);
Server에서 사용 가능한 버전은 현재 존재하긴 하는데 SSR 관련 문제가 발생해서 이렇게 임시조치 해놨어요!
훅으로 빼 놓는게 공통으로 사용할 수 있어서 좋아보여요!
아래 내용 한번 읽어보셔도 될 듯 합니다
https://github.com/Project-aniwhere/Aniwhere-FE/wiki/%EC%BA%90%EB%9F%AC%EC%83%90%EC%9D%98-%EC%B4%88%EA%B8%B0%EA%B0%92%EC%9D%84-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0-%EC%9C%84%ED%95%B4

2024-11-06 11:48 UTC, LEEGURTS commented
![image](https://github.com/user-attachments/assets/c4e9af38-5b9d-44ee-b52a-c0bbec32daed)
![image](https://github.com/user-attachments/assets/69ad14b7-f052-46f9-b430-adbef466645d)
오랜만에 보는 초록색입니다
실제 배포에도 이랬으면 좋겠네요

2024-11-07 13:43 UTC, yujinyny approved these changes
고생하셨습니다!

2024-11-07 14:24 UTC, merged