[FEAT] footer generate #1
Project-aniwhere/Aniwhere-FE pull request #8
Opened 2024-10-24 13:25 UTC by Programmer-JK

## footer 초기 등록

## 작업 상세 내용

- [ Y ] 기본적인 footer 생성

## 기타 내용
- 추후 자세한 디자인 및 내용 추가할 예정

2024-10-25 05:47 UTC, LEEGURTS commented
- 치고 [x]로 입력하면 빈칸이 메꿔집니다

2024-10-26 12:33 UTC, yujinyny approved these changes
확인했습니다!

2024-10-26 14:24 UTC, LEEGURTS requested changes

2024-10-26 14:24 UTC, LEEGURTS commented on src/common/footer/footer.tsx
> +      <h2 className='font-bold text-3xl leading-snug'>Aniwhere</h2>
snug 대신 가능하면 rem 단위로 개발해주셨으면 합니다!

2024-10-26 14:24 UTC, LEEGURTS commented on src/common/footer/footer.tsx
> +    <footer className='mt-20 p-5 w-full relative text-center bg-aniviolet3 text-white'>
아마 컨텐츠 요소를 잘 배치하면 margin을 굳이 쓸 필요 없을듯 해요. 본 layout에서 padding이랑 max-width, gap 설정이 아직 안되어 있기도 합니다

2024-10-26 14:24 UTC, LEEGURTS commented on src/common/footer/footer.tsx
> +'use client';
client랑 상호작용 하는 부분이 없어서 use client 선언은 필요 없어보입니다

2024-10-27 05:41 UTC, Programmer-JK commented on src/common/footer/footer.tsx
> +      <h2 className='font-bold text-3xl leading-snug'>Aniwhere</h2>
네, 알겠습니다

2024-10-27 05:41 UTC, Programmer-JK commented on src/common/footer/footer.tsx
> +'use client';
아하, 네! 알겠습니다

2024-10-27 12:56 UTC, LEEGURTS commented on src/common/footer/footer.tsx
> +            xmlns='http://www.w3.org/2000/svg'
Svg 요소는 svg 파일이던 컴포넌트던 빼주셨으면 합니다

2024-10-27 12:56 UTC, LEEGURTS commented on src/common/footer/footer.tsx
> +        <a>팀 깃허브</a>
넥스트는 Link라는 라우팅 수단을 제공합니다

2024-10-27 12:56 UTC, Programmer-JK commented on src/common/footer/footer.tsx
> +            xmlns='http://www.w3.org/2000/svg'
네, 알겠습니다

2024-10-27 12:57 UTC, Programmer-JK commented on src/common/footer/footer.tsx
> +        <a>팀 깃허브</a>
그럼 Link 태그 써서 수정하겠습니다

2024-10-27 13:01 UTC, LEEGURTS approved these changes

2024-10-27 13:58 UTC, merged