Feat/common component
Project-aniwhere/Aniwhere-FE pull request #9
Opened 2024-10-25 01:21 UTC by LEEGURTS

## 이슈 번호, 혹은 추가한 기능에 대해 설명해주세요.
#6

## 작업 상세 내용

- [x] 캐러셀 구현

## 기타 내용

2024-10-26 13:36 UTC, yujinyny requested changes

2024-10-26 13:36 UTC, yujinyny commented on src/app/(home)/page.tsx
> +const Video = ({
Video 별도 컴포넌트 파일로 분리하는게 어떨까요?

2024-10-26 13:36 UTC, yujinyny commented on src/common/carousel/bullet.tsx
> +const BulletItem = () => {
이 부분도 별도 컴포넌트로 분리하는 것을 의견드립니다

2024-10-26 13:36 UTC, yujinyny commented on src/common/carousel/carousel-container.tsx
> +const ArrowButton = ({
이 부분도 별도 컴포넌트로 분리하는 것을 의견드립니다

2024-10-26 13:36 UTC, yujinyny commented on src/common/carousel/bullet.tsx
> +    <div className='bullet-item'>
현재 파일에서 bullet-item, bullet, carousel-bullet은 별도의 class를 지정해서 스타일을 관리하시는 이유가 있나요?

2024-10-26 14:19 UTC, LEEGURTS commented on src/common/carousel/bullet.tsx
> +    <div className='bullet-item'>
아녀 임시구현이라 대충 넣어놨어요

2024-10-28 01:46 UTC, yujinyny approved these changes
고생하셨습니다 :)

2024-10-28 05:09 UTC, merged